version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.10.3
    - 3.10.4
    - 3.10.5
    - 3.10.6
    - 3.8.1
    - 3.8.2
    - 3.9.1
    - 3.9.2
    - 3.9.3
    - 4.0.0
    - 4.0.1
    - 4.0.2
    - 4.0.3
    - 4.1.0
    - 4.1.10
    - 4.1.2
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.1.6
    - 4.1.7
    - 4.1.8
    - 4.1.9
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@stitches/react"
    versions:
    - 0.1.0
    - 0.1.0-canary.14
    - 0.1.0-canary.15
    - 0.1.0-canary.16
    - 0.1.0-canary.17
    - 0.1.0-canary.18
    - 0.1.0-canary.19
    - 0.1.0-canary.20
    - 0.1.0-canary.21
    - 0.1.1
    - 0.1.2
    - 0.1.3
    - 0.1.4
    - 0.1.5
    - 0.1.6
    - 0.1.7
    - 0.1.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@reach/visually-hidden"
    versions:
    - 0.14.0
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.1.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.0
  - dependency-name: polished
    versions:
    - 4.1.0
    - 4.1.1
  - dependency-name: "@emotion/babel-preset-css-prop"
    versions:
    - 11.0.0
    - 11.2.0
  - dependency-name: "@emotion/babel-plugin"
    versions:
    - 11.1.2
    - 11.2.0
  - dependency-name: "@emotion/react"
    versions:
    - 11.1.4
    - 11.1.5
  - dependency-name: react-is
    versions:
    - 17.0.1
  - dependency-name: "@emotion/css"
    versions:
    - 11.1.3
  - dependency-name: react-syntax-highlighter
    versions:
    - 15.4.3
  - dependency-name: "@emotion/server"
    versions:
    - 11.0.0
