name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: yarn lint
        run: yarn lint
        env:
          CI: true
