name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: npm ci
      run: npm ci
    - name: npm run lint
      run: npm run lint
      env:
        CI: true
