name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: pnpm install
        run: pnpm install --frozen-lockfile
      - name: pnpm lint
        run: pnpm lint
        env:
          CI: true
